version: 2
updates:

- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
    timezone: UTC
  open-pull-requests-limit: 10
  commit-message:
      prefix: "chore"
      include: "scope"
  labels:
     - "dependabot"
     - "dependencies"


- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
    timezone: UTC
  open-pull-requests-limit: 10
  commit-message:
      prefix: "chore"
      include: "scope"
  labels:
     - "dependabot"
     - "dependencies"